name: Python package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.3.2'
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-root

      - name: Check if version exists on PyPI
        run: |
          PACKAGE_VERSION=$(poetry version --short)
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://pypi.org/pypi/mongorepository/$PACKAGE_VERSION/json)
          if [ "$RESPONSE" == "200" ]; then
            echo "Version $PACKAGE_VERSION already exists on PyPI. Skipping publish."
            echo "EXISTS=true" >> $GITHUB_ENV
          else
            echo "Version $PACKAGE_VERSION does not exist on PyPI. Proceeding with publish."
            echo "EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Publish to PyPI
        env:
          EXISTS: ${{ env.EXISTS }}
        if: env.EXISTS == 'false'
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build