name: Deploy Documentation

on:
  workflow_call:

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest

    steps:          
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.3.2'
      
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'

      - name: Install requirements
        run: poetry install --only semver

      - name: Install dependencies
        run: poetry add sphinx sphinx-rtd-theme

      - name: Generate docs
        run: |
          cd docs
          make html

      - name: Publish in branch `gh-pages`
        run: |
          git worktree add -B gh-pages ../gh-pages origin/gh-pages
          cp -r _build/html/* ../gh-pages
          cd ../gh-pages
          git add .
          git commit -m "Atualizar documentação"
          git push origin gh-pages
