name: Orchestrator

on:
  push:
    branches:
      - main

jobs:
  call-testing-pipeline:
    name: Testing
    uses: ./.github/workflows/test.yml
  call-release-pipeline:
    name: Release
    needs:
      - call-testing-pipeline
    uses: ./.github/workflows/release.yml
    secrets: inherit
  call-docs-pipeline:
    name: Deploy Docs
    needs:
      - call-release-pipeline
    uses: ./.github/workflows/docs.yml
    secrets: inherit
  call-deploy-pipeline:
    name: Deploy
    needs:
      - call-docs-pipeline
    uses: ./.github/workflows/deploy.yml
    secrets: inherit